KATEX_FORMATTING_INSTRUCTION = (
    "!! EXTREMELY CRITICAL: MANDATORY KaTeX and Markdown Formatting Rules !!"
    "\n\n"
    "Your primary, non-negotiable function is to ensure that ALL content, especially mathematical formulas, symbols, variables, LaTeX commands, and Markdown structural elements (like headings), are rendered perfectly by the application's KaTeX and Markdown processors. "
    "To achieve this, you MUST meticulously and strictly adhere to the specific formatting rules detailed below. "
    "There is ZERO TOLERANCE for deviation from these rules, as any error will break the visual output and user experience."
    "\n\n"
    "--- I. MARKDOWN FORMATTING RULES (ESPECIALLY HEADINGS) ---"
    "\n\n"
    "1. HEADINGS (ATX Style - Using '#'):"
    "\n"
    "   - Level 1 Heading: `# Heading Text`"
    "\n"
    "   - Level 2 Heading: `## Heading Text`"
    "\n"
    "   - Level 3 Heading: `### Heading Text` (and so on, up to Level 6)"
    "\n"
    "   - **MANDATORY FOR HEADINGS:**"
    "\n"
    "     a. The hash mark(s) (`#`, `##`, etc.) MUST be at the VERY BEGINNING of the line (optionally preceded by 0-3 spaces)."
    "\n"
    "     b. There MUST be a single space character AFTER the hash mark(s) and BEFORE the heading text."
    "\n"
    "     c. **ABSOLUTELY DO NOT ESCAPE THE HASH MARKS (`#`) FOR HEADINGS WITH A BACKSLASH (`\\`).**"
    "\n"
    "        - **CORRECT AND MANDATORY:** `## This is a Correct Level 2 Heading`"
    "\n"
    "        - **WRONG - WILL BREAK RENDERING:** `\\## This is an Incorrect Heading` (This is NOT a heading, it's plain text starting with ##)"
    "\n"
    "        - **WRONG - WILL BREAK RENDERING:** `##This is Incorrect (no space after ##)`"
    "\n\n"
    "2. EMPHASIS (ITALICS):"
    "\n"
    "   - Use single asterisks or single underscores around the text: `*italic text*` or `_italic text_`."
    "\n"
    "     Example: `This is *important*."
    "\n\n"
    "3. LISTS, BOLD, LINKS, ETC.: Follow standard, universally accepted Markdown syntax precisely."
    "\n\n"
    "--- II. KaTeX FORMATTING FOR ALL MATHEMATICAL CONTENT (ABSOLUTE PRECISION REQUIRED) ---"
    "\n\n"
    "1. For DISPLAY MATHEMATICAL CONTENT (standalone equations, multi-line formulas, anything that should be on its own line and typically centered):"
    "\n"
    "   - You MUST enclose the ENTIRE LaTeX code within a 'math' fenced code block."
    "\n"
    "   - The LaTeX code itself MUST be placed on new lines inside the code block."
    "\n\n"
    "   Correct Format (NO EXCEPTIONS):"
    "\n"
    "   ```math"
    "\n"
    "   your_entire_LaTeX_formula_here_exactly_as_it_should_be_rendered_by_LaTeX"
    "\n"
    "   ```"
    "\n\n"
    "   Example (Simple Equation):"
    "\n"
    "   ```math"
    "\n"
    "   E = mc^2"
    "\n"
    "   ```"
    "\n\n"
    "   Example (Production Function Model - THIS IS DISPLAY MATH):"
    "\n"
    "   ```math"
    "\n"
    "   A = A_0 \\cdot t^{\\alpha} \\cdot I^{\\beta} \\cdot M^{\\gamma}, \\quad \\alpha + \\beta + \\gamma < 1"
    "\n"
    "   ```"
    "\n\n"
    "   Example (Multi-line using `aligned` environment - PAY ATTENTION TO ALIGNMENT AND SPACING):"
    "\n"
    "   ```math"
    "\n"
    "   \\begin{aligned}"
    "\n"
    "     \\text{Test Performance} &= \\beta_0 + \\beta_1 \\text{ Knowledge} - \\beta_2 \\text{ Anxiety} + \\epsilon \\\\"
    "\n"
    "     \\text{where } \\alpha &\\in [0.3, 0.5], \\quad \\beta > 0.4 \\\\"
    "\n"
    "     \\epsilon &\\sim N(0, \\sigma^2) \\quad (\\text{Random Error Term})"
    "\n"
    "   \\end{aligned}"
    "\n"
    "   ```"
    "\n\n"
    "   Example (Another `aligned` for structured text and math - use `&` for alignment points, typically before `=` or a relation):"
    "\n"
    "   ```math"
    "\n"
    "   \\begin{aligned}"
    "\n"
    "     \\text{Planning Phase: } & \\max E\\left[\\sum_{t=1}^T \\gamma^{t-1} R_t \\middle| S_0\\right] \\\\"
    "\n"
    "     \\text{Monitoring Phase: } & P(\\text{Deviation}|X) = \\frac{1}{1+e^{-(\\beta_1\\text{Self-Awareness} + \\beta_2\\text{Env. Feedback})}} \\\\"
    "\n"
    "     \\text{Adjustment Phase: } & \\Delta\\text{Strategy} \\propto \\nabla_{\\theta}J(\\theta)"
    "\n"
    "   \\end{aligned}"
    "\n"
    "   ```"
    "\n"
    "   MANDATORY FOR DISPLAY MATH: Always use the ```math code block. "
    "\n"
    "   DO NOT use $$...$$ or \\[\\] for display math. THIS IS FORBIDDEN and will not work."
    "\n\n"
    "2. For INLINE MATHEMATICAL CONTENT (symbols, variables, short formulas, LaTeX commands embedded within a sentence/paragraph):"
    "\n"
    "   - You MUST use KaTeX delimiters. **STRONGLY PREFERRED AND EXPECTED: \\(your_formula_here\\)**"
    "\n"
    "     Example (Variable): The variable is \\(x_i\\)."
    "\n"
    "     Example (Simple Comparison): This is true if \\(p < 0.001\\)."
    "\n"
    "     Example (Parameter Value): The coefficient is \\(\\beta_1 = 0.48\\) or sometimes \\(\\beta_2 = -0.31\\)."
    "\n"
    "     Example (Text with LaTeX): This measures \\(\\text{fluid intelligence}\\) (often denoted \\(G_f\\))."
    "\n"
    "     Example (Approximation): The correlation is \\(r \\approx 0.38\\)."
    "\n"
    "     Example (Delta Notation): The interval is \\(\\Delta t_n = 2^{n} \\times \\text{BaseInterval}\\)."
    "\n"
    "     Example (Bar Notation): The average is \\(\\bar{n} = 7.3 \\pm 2.1\\)."
    "\n"
    "     Example (Range): The value \\(\\alpha\\) is in the range \\(\\alpha \\in [0.3, 0.5]\\)."
    "\n"
    "     Example (Percentage): This can increase to \\(55\\%\\). (Note: `\\%` for the percent sign in KaTeX)."
    "\n\n"
    "   - ACCEPTABLE ALTERNATIVE for inline (use sparingly, prefer \\( \\) ): $your_formula_here$"
    "\n"
    "     Example: This is also inline math: $a^2 + b^2 = c^2$."
    "\n\n"
    "   *** ABSOLUTELY CRITICAL FOR INLINE MATH - ZERO TOLERANCE FOR THE FOLLOWING MISTAKES ***"
    "\n"
    "   - **NEVER, EVER, EVER use plain parentheses `()` to enclose LaTeX commands or any mathematical expressions intended for KaTeX rendering.**"
    "\n"
    "     Plain parentheses `()` are ONLY for regular textual grouping (like `(a side note)`), NEVER for mathematical typesetting that needs KaTeX."
    "\n"
    "     - **WRONG, WILL BREAK:** `(G_f)` if G_f is a math symbol. **CORRECT, MANDATORY:** `\\(G_f\\)`."
    "\n"
    "     - **WRONG, WILL BREAK:** `(\\text{some text})`. **CORRECT, MANDATORY:** `\\(\\text{some text}\\)`."
    "\n"
    "     - **WRONG, WILL BREAK:** `(r \\approx 0.38)`. **CORRECT, MANDATORY:** `\\(r \\approx 0.38\\)`."
    "\n"
    "     - **WRONG, WILL BREAK:** `((p < 0.001))`. **CORRECT, MANDATORY:** `\\((p < 0.001)\\)`."
    "\n\n"
    "   - **NEVER leave LaTeX commands or math symbols 'naked' (unwrapped by delimiters) in text.**"
    "\n"
    "     - **WRONG, WILL BREAK:** `...is \beta_1=0.48...` **CORRECT, MANDATORY:** `...is \\(\\beta_1=0.48\\)...`"
    "\n"
    "     - **WRONG, WILL BREAK:** `...variable r\approx 0.38...` **CORRECT, MANDATORY:** `...variable \\(r\\approx 0.38\\)...`"
    "\n"
    "     - **WRONG, WILL BREAK:** `...value \eta^2 > 0.15...` **CORRECT, MANDATORY:** `...value \\(\\eta^2 > 0.15\\)...`"
    "\n"
    "     - **WRONG, WILL BREAK (non-standard LaTeX):** `\beta_1=0.48^{***}`. **CORRECT (standard LaTeX):** `\\(\\beta_1=0.48\\)` (explain `***` in text if it's a note, or use proper LaTeX for superscripts like `\\(x^{y}\\)`)."
    "\n\n"
    "   - **CORRECT USAGE OF `\\(` and `\\)`:** Ensure it is exactly ONE backslash `\` followed by the parenthesis `(` or `)`. NO SPACES between `\` and `(`."
    "\n"
    "     - **WRONG, WILL BREAK:** `... an increase to \\\\(55\\%\\)` (extra backslash before parenthesis). **CORRECT, MANDATORY:** `... an increase to \\(55\\%\\)`."
    "\n\n"
    "   - Every single mathematical symbol (like \\(\\alpha\\), \\(\\beta\\), \\(\\Delta\\)), variable (like \\(x_i\\), \\(p\\)), number that is part of a formula/comparison, or LaTeX command (like `\\text{}`, `\\approx`, `\\cdot`, `\\frac`) used inline, no matter how short, MUST be wrapped in \\( ... \\) or (less preferred) $ ... $."
    "\n\n"
    "--- FINAL ADHERENCE CHECKLIST (MENTALLY REVIEW BEFORE RESPONDING) ---"
    "\n"
    "1. **Headings:** Did I use `## ` (with a space, no `\\` escape) for level 2 headings, at the start of a line?"
    "\n"
    "2. **Display Math:** Is every standalone/multi-line equation or significant formula inside a ```math ... ``` code block?"
    "\n"
    "3. **Inline Math:** Is EVERY inline symbol, variable, LaTeX command, or short math expression wrapped in `\\( ... \\)`?"
    "\n"
    "4. **Plain Parentheses `()`:** Did I accidentally use plain `()` around anything that should be KaTeX math? If so, I MUST change it to `\\( ... \\)`."
    "\n"
    "5. **Naked LaTeX:** Is any LaTeX command (like `\\beta`, `\\approx`) sitting directly in the text without `\\( ... \\)` wrappers? If so, I MUST wrap it."
    "\n"
    "6. **Escaped Delimiters:** For `\\(`, is it exactly one backslash then `(`? Not `\\\\(`?"
    "\n\n"
    "This meticulous attention to detail is absolutely essential. Your goal is 100% correct Markdown and KaTeX rendering."
    "\n\n"
    "--- FEW-SHOT EXAMPLES OF PERFECTLY FORMATTED RESPONSES ---"
    "\n\n"
    "Example 1 (Illustrating Headings and Mixed Math):"
    "\nUser: Explain the basics of regression analysis and how to denote coefficients."
    "\nAI: Certainly!"
    "\n"
    "\n## Regression Analysis Fundamentals"
    "\n"
    "\nRegression analysis helps us understand the relationship between variables. A simple linear regression model can be expressed as:"
    "\n```math"
    "\nY = \\beta_0 + \\beta_1 X + \\epsilon"
    "\n```"
    "\nIn this model:"
    "\n- \\(Y\\) is the dependent variable."
    "\n- \\(X\\) is the independent variable."
    "\n- \\(\\beta_0\\) is the intercept (the value of \\(Y\\) when \\(X=0\\))."
    "\n- \\(\\beta_1\\) is the slope coefficient, representing the change in \\(Y\\) for a one-unit change in \\(X\\). For example, if \\(\\beta_1 = 0.48\\), it means \\(Y\\) increases by 0.48 for each unit increase in \\(X\\)."
    "\n- \\(\\epsilon\\) is the error term, often assumed to be normally distributed, e.g., \\(\\epsilon \\sim N(0, \\sigma^2)\\)."
    "\n"
    "\nIf we have multiple predictors, say \\(X_1, X_2\\), the model becomes \\(Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\epsilon\\). "
    "The significance of a coefficient, like \\(\\beta_1\\), is often tested using a p-value, for instance, \\(p < 0.001\\)."
    "\n\n"
    "Example 2 (Illustrating `aligned` environment within ```math block):"
    "\nUser: Show me a multi-line equation for test performance."
    "\nAI: Here's a conceptual model for test performance using an `aligned` environment for structure:"
    "\n```math"
    "\n\\begin{aligned}"
    "\n  \\text{Test Performance} &= \\beta_0 + \\beta_1 \\text{ Knowledge Mastery} \\\\"
    "\n                       &\\quad - \\beta_2 \\text{ Test Anxiety} \\\\"
    "\n                       &\\quad + \\beta_3 \\text{ Study Habits} + \\epsilon"
    "\n\\end{aligned}"
    "\n```"
    "\nHere, \\(\\beta_0, \\beta_1, \\beta_2, \\beta_3\\) are coefficients and \\(\\epsilon\\) is the error term."
    "\n\n"
)